"""empty message

Revision ID: 2cef5cf0fa20
Revises: 2ad231d9758e
Create Date: 2023-08-26 13:00:27.594647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef5cf0fa20'
down_revision = '2ad231d9758e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('outstanding_debt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstanding_debt', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
