"""empty message

Revision ID: 695505648be4
Revises: e975d1b25f65
Create Date: 2023-08-25 23:59:59.151727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695505648be4'
down_revision = 'e975d1b25f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latefee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('latefee')

    # ### end Alembic commands ###
