"""empty message

Revision ID: 9bd50a76fba0
Revises: d17d01aa6452
Create Date: 2023-08-26 00:17:35.938790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd50a76fba0'
down_revision = 'd17d01aa6452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('outstanding_debt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstanding_debt', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
