"""empty message

Revision ID: a96fd36a550e
Revises: 2cef5cf0fa20
Create Date: 2023-08-26 23:28:14.113513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96fd36a550e'
down_revision = '2cef5cf0fa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('available_quanity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_quanity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('available_quantity')

    # ### end Alembic commands ###
