"""empty message

Revision ID: e975d1b25f65
Revises: fe1dfcc98005
Create Date: 2023-08-25 23:58:58.721213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e975d1b25f65'
down_revision = 'fe1dfcc98005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rentfee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charges')
    # ### end Alembic commands ###
